{% set name = "pymeos" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f941599d6f836d785c3b9ae14b53dc86fcb67881e5b5669ec8c2804245f4d7a0

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  # meos and pymeos-cffi is not available on win-64 and s390x
  skip: True  # [s390x or win or py<38]

requirements:
  host:
    - python
    - setuptools >=61.0
    - wheel
    - pip
  run:
    - python
    - pymeos-cffi >=1.2.0,<2
    - python-dateutil
    - shapely >=2.0.0
  run_constrained:
    # dbp
    - psycopg
    # dbp2 
    - psycopg2
    # dba
    - asyncpg
    # plot 
    - matplotlib
    # pandas 
    - geopandas

test:
  imports:
    - pymeos
  commands:
    - pip check
    - python -c "import pymeos; pymeos.pymeos_initialize('UTC'); pymeos.pymeos_finalize();"
  requires:
    - python
    - pip

about:
  summary: Python wrapper for the MEOS C Library.
  description: |
    PyMEOS is a Python library exposing an object-oriented API for the MEOS C Library. It wraps all the exposed
    functions in easy-to-use classes, allowing the user to perform operations on temporal and spatiotemporal data
    in Python without having to worry about the underlying C code.
  license: PostgreSQL
  license_file: LICENSE.txt
  license_family: OTHER
  home: https://pymeos.readthedocs.io
  doc_url: https://pymeos.readthedocs.io
  dev_url: https://github.com/MobilityDB/PyMEOS

extra:
  recipe-maintainers:
    - Diviloper
    - estebanzimanyi
